# Generated by Django 5.0.4 on 2024-04-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
