# Generated by Django 5.0.4 on 2024-04-05 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=150, unique=True)),
                ("category_slug", models.CharField(max_length=150, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Uav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                ("brand", models.CharField(max_length=150)),
                ("model", models.CharField(max_length=50)),
                ("year", models.DateField()),
                ("weight", models.IntegerField()),
                ("features", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Passive", "Passive")],
                        default="Passive",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ihas.category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "uavs",
            },
        ),
    ]
