# Generated by Django 5.0.4 on 2024-04-05 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ihas", "0002_rental"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rental",
            name="end_date",
        ),
    ]
