# Generated by Django 5.0.4 on 2024-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ihas", "0003_remove_rental_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="end_date",
            field=models.DateField(default="2024-01-01"),
        ),
        migrations.AlterField(
            model_name="rental",
            name="start_date",
            field=models.DateField(default="2024-01-01"),
        ),
    ]
