# Generated by Django 5.0.4 on 2024-04-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ihas", "0005_rental_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rental",
            name="price",
        ),
        migrations.AddField(
            model_name="rental",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="uav",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
