# Generated by Django 5.0.4 on 2024-04-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ihas", "0006_remove_rental_price_rental_total_price_uav_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="end_date",
            field=models.DateTimeField(default="2024-01-01"),
        ),
        migrations.AlterField(
            model_name="rental",
            name="start_date",
            field=models.DateTimeField(default="2024-01-01"),
        ),
    ]
