# Generated by Django 5.0.4 on 2024-04-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ihas", "0007_alter_rental_end_date_alter_rental_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="uav",
            name="image",
            field=models.ImageField(
                blank=True, default="uploads/default.jpg", upload_to="uploads/%Y/%m/%d"
            ),
        ),
    ]
